### ISSUE TITLE
bug(permalinks): TypeError: Unicode-objects must be encoded before hashing

### ISSUE THREAD

**Issue by Kristinita** [getpelican/pelican-plugins#1011]
@cscutcher, ping.

### 1. Summary

permalinks plugin doesn't work for me. I get traceback in console:

```python
ERROR: Could not process SashaContent/SashaPermalinks.md
  | TypeError: Unicode-objects must be encoded before hashing
  |___
  | Traceback (most recent call last):
  |   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pelican/generators.py", line 523, in generate_context
  |     context_sender=self)
  |   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pelican/readers.py", line 572, in read_file
  |     context=context)
  |   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pelican/contents.py", line 153, in __init__
  |     signals.content_object_init.send(self)
  |   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/blinker/base.py", line 267, in send
  |     for receiver in self.receivers_for(sender)]
  |   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/blinker/base.py", line 267, in <listcomp>
  |     for receiver in self.receivers_for(sender)]
  |   File "/home/travis/build/Kristinita/KristinitaPelican/pelican-plugins/filetime_from_git/registration.py", line 15, in send_content_git_object_init
  |     content_git_object_init.send(content, git_content=GitContentAdapter(content))
  |   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/blinker/base.py", line 267, in send
  |     for receiver in self.receivers_for(sender)]
  |   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/blinker/base.py", line 267, in <listcomp>
  |     for receiver in self.receivers_for(sender)]
  |   File "/home/travis/build/Kristinita/KristinitaPelican/pelican-plugins/filetime_from_git/actions.py", line 98, in git_permalink
  |     permalink_hash.update(str(git_content.get_oldest_commit()))
  | TypeError: Unicode-objects must be encoded before hashing
```

### 2. Environment

+ Operating systems:

    + Windows 10 Enterprise LTSB 64-bit EN (local),
    + Ubuntu 14.04.5 LTS ([**Travis CI**](https://travis-ci.org/Kristinita/KristinitaPelican/jobs/363183318#L526-L549)),
    + Windows Server 2016 ([**AppVeyor**](https://ci.appveyor.com/project/Kristinita/kristinitapelican/build/1.0.19#L97)).

+ Python 3.6.5,
+ gitpython 2.1.9,
+ Python Markdown 2.6.11,
+ Pelican 3.7.1,
+ filetime_from_git — [**@aufarg patch version**](https://github.com/getpelican/pelican-plugins/pull/1002),
+ permalinks 2016.9.22.

### 3. Configuration

See full configuration on [**SashaPermalinks branch**](https://github.com/Kristinita/KristinitaPelican/tree/SashaPermalinks) of my demo repository.

[**pelican-quickstart**](http://docs.getpelican.com/en/latest/quickstart.html#create-a-project) → I add [**1 article**](https://github.com/Kristinita/KristinitaPelican/blob/SashaPermalinks/content/SashaContent/SashaPermalinks.md) and [**`filetime_from_git` and `permalinks` plugins**](https://github.com/Kristinita/KristinitaPelican/tree/SashaPermalinks/pelican-plugins) → I add to [**`pelicanconf.py`**](https://github.com/Kristinita/KristinitaPelican/blob/SashaPermalinks/pelicanconf.py) lines:

```python
PLUGIN_PATHS = ['pelican-plugins']
PLUGINS = [
    'filetime_from_git',
    'permalinks',
]

GIT_HISTORY_FOLLOWS_RENAME = True
GIT_GENERATE_PERMALINK = True
GIT_SHA_METADATA = True
GIT_FILETIME_FROM_GIT = True

ARTICLE_PATHS = ['SashaContent']
```

### 4. Steps to reproduce

I run in console:

    pelican content -s pelicanconf.py

### 5. Expected behavior

Successful permalinks usage.

### 6. Actual behavior

+ [**Travis CI**](https://travis-ci.org/Kristinita/KristinitaPelican/jobs/363183318#L526-L549),
+ [**AppVeyor**](https://ci.appveyor.com/project/Kristinita/kristinitapelican/build/1.0.19#L97).

```python
ERROR: Could not process SashaContent/SashaPermalinks.md
  | TypeError: Unicode-objects must be encoded before hashing
  |___
  | Traceback (most recent call last):
  |   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pelican/generators.py", line 523, in generate_context
  |     context_sender=self)
  |   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pelican/readers.py", line 572, in read_file
  |     context=context)
  |   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pelican/contents.py", line 153, in __init__
  |     signals.content_object_init.send(self)
  |   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/blinker/base.py", line 267, in send
  |     for receiver in self.receivers_for(sender)]
  |   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/blinker/base.py", line 267, in <listcomp>
  |     for receiver in self.receivers_for(sender)]
  |   File "/home/travis/build/Kristinita/KristinitaPelican/pelican-plugins/filetime_from_git/registration.py", line 15, in send_content_git_object_init
  |     content_git_object_init.send(content, git_content=GitContentAdapter(content))
  |   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/blinker/base.py", line 267, in send
  |     for receiver in self.receivers_for(sender)]
  |   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/blinker/base.py", line 267, in <listcomp>
  |     for receiver in self.receivers_for(sender)]
  |   File "/home/travis/build/Kristinita/KristinitaPelican/pelican-plugins/filetime_from_git/actions.py", line 98, in git_permalink
  |     permalink_hash.update(str(git_content.get_oldest_commit()))
  | TypeError: Unicode-objects must be encoded before hashing
```

Thanks.

**Comment by cscutcher** [comment]
Looking at this now. PR incoming shortly
