### ISSUE TITLE
rmd_reader fails with rpy2 >=3.0

### ISSUE THREAD

**Issue by stephenfeagin** [getpelican/pelican-plugins#1132]
Using Python 3.6.7, when I run `python test_rmd_reader.py`, all three tests error out. The output is shown below. In all three cases, the error is 

> `AttributeError: module 'rpy2.rinterface' has no attribute 'set_initoptions'`

In moving to version 3.0.0 back in February, rpy2 made some pretty major changes in the API, including getting rid of `rinterface.set_initoptions()`. 

I'd be happy to work on making the plugin compatible with rpy2 >= 3.0.0 (though I may need some guidance on getting my environment set up). In the meantime, it may be useful to mention in the README that you need to pin rpy2 to 2.9.5 or earlier.

Test output:

```
DEBUG:root:/home/stephen/Projects/pelican-assets/pelican-plugins/rmd_reader
DEBUG:root:/home/stephen/Projects/pelican-assets/pelican-plugins/rmd_reader/test-content
DEBUG:root:/home/stephen/Projects/pelican-assets/pelican-plugins/rmd_reader/test-content/test.rmd
DEBUG:root:/home/stephen/Projects/pelican-assets/pelican-plugins/rmd_reader/test-output
WARNING:pelican.settings:Feeds generated without SITEURL set properly may not be valid
WARNING:pelican.settings:No timezone information specified in the settings. Assuming your timezone is UTC for feed generation. Check http://docs.getpelican.com/en/latest/settings.html#timezone for more information
DEBUG:pelican:Adding current directory to system path
DEBUG:pelican:Temporarily adding PLUGIN_PATHS to system path
DEBUG:pelican:Loading plugin `rmd_reader`
DEBUG:pelican:Registering plugin `rmd_reader`
DEBUG:pelican:Restoring system path
DEBUG:RMD_READER:STARTING R
DEBUG:root:CLEAN
EDEBUG:root:/home/stephen/Projects/pelican-assets/pelican-plugins/rmd_reader
DEBUG:root:/home/stephen/Projects/pelican-assets/pelican-plugins/rmd_reader/test-content
DEBUG:root:/home/stephen/Projects/pelican-assets/pelican-plugins/rmd_reader/test-content/test.rmd
DEBUG:root:/home/stephen/Projects/pelican-assets/pelican-plugins/rmd_reader/test-output
DEBUG:root:CLEAN
EDEBUG:root:/home/stephen/Projects/pelican-assets/pelican-plugins/rmd_reader
DEBUG:root:/home/stephen/Projects/pelican-assets/pelican-plugins/rmd_reader/test-content
DEBUG:root:/home/stephen/Projects/pelican-assets/pelican-plugins/rmd_reader/test-content/test.rmd
DEBUG:root:/home/stephen/Projects/pelican-assets/pelican-plugins/rmd_reader/test-output
DEBUG:root:CLEAN
E
======================================================================
ERROR: testKnitrSettings (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_rmd_reader.py", line 83, in testKnitrSettings
    pelican = Pelican(settings=settings)
  File "/home/stephen/virtualenvs/rmd_reader/lib/python3.6/site-packages/pelican/__init__.py", line 58, in __init__
    signals.initialized.send(self)
  File "/home/stephen/virtualenvs/rmd_reader/lib/python3.6/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/home/stephen/virtualenvs/rmd_reader/lib/python3.6/site-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/home/stephen/Projects/pelican-assets/pelican-plugins/rmd_reader/rmd_reader.py", line 39, in initsignal
    startr()
  File "/home/stephen/Projects/pelican-assets/pelican-plugins/rmd_reader/rmd_reader.py", line 27, in startr
    rpy2.rinterface.set_initoptions((b'rpy2', b'--no-save', b'--vanilla',
AttributeError: module 'rpy2.rinterface' has no attribute 'set_initoptions'

======================================================================
ERROR: testKnitrSettings2 (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_rmd_reader.py", line 116, in testKnitrSettings2
    pelican = Pelican(settings=settings)
  File "/home/stephen/virtualenvs/rmd_reader/lib/python3.6/site-packages/pelican/__init__.py", line 58, in __init__
    signals.initialized.send(self)
  File "/home/stephen/virtualenvs/rmd_reader/lib/python3.6/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/home/stephen/virtualenvs/rmd_reader/lib/python3.6/site-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/home/stephen/Projects/pelican-assets/pelican-plugins/rmd_reader/rmd_reader.py", line 39, in initsignal
    startr()
  File "/home/stephen/Projects/pelican-assets/pelican-plugins/rmd_reader/rmd_reader.py", line 27, in startr
    rpy2.rinterface.set_initoptions((b'rpy2', b'--no-save', b'--vanilla',
AttributeError: module 'rpy2.rinterface' has no attribute 'set_initoptions'

======================================================================
ERROR: testKnitrSettings3 (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_rmd_reader.py", line 152, in testKnitrSettings3
    pelican = Pelican(settings=settings)
  File "/home/stephen/virtualenvs/rmd_reader/lib/python3.6/site-packages/pelican/__init__.py", line 58, in __init__
    signals.initialized.send(self)
  File "/home/stephen/virtualenvs/rmd_reader/lib/python3.6/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/home/stephen/virtualenvs/rmd_reader/lib/python3.6/site-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/home/stephen/Projects/pelican-assets/pelican-plugins/rmd_reader/rmd_reader.py", line 39, in initsignal
    startr()
  File "/home/stephen/Projects/pelican-assets/pelican-plugins/rmd_reader/rmd_reader.py", line 27, in startr
    rpy2.rinterface.set_initoptions((b'rpy2', b'--no-save', b'--vanilla',
AttributeError: module 'rpy2.rinterface' has no attribute 'set_initoptions'

----------------------------------------------------------------------
Ran 3 tests in 0.031s

FAILED (errors=3)
```

`pip freeze`:

```
atomicwrites==1.3.0
attrs==19.1.0
blinker==1.4
cffi==1.12.3
docutils==0.14
entrypoints==0.3
feedgenerator==1.9
flake8==3.7.7
Jinja2==2.10.1
MarkupSafe==1.1.1
mccabe==0.6.1
more-itertools==7.0.0
pelican==4.0.1
pluggy==0.9.0
py==1.8.0
pycodestyle==2.5.0
pycparser==2.19
pyflakes==2.1.1
Pygments==2.3.1
pytest==4.4.1
python-dateutil==2.8.0
pytz==2019.1
rpy2==3.0.2
simplegeneric==0.8.1
six==1.12.0
Unidecode==1.0.23
```

**Comment by carlosal1015** [comment]
Testing with rpy2==2.9.5 and works :smile:

**Comment by Lucas-C** [comment]
I got the issue with `rpy2 3.1.0` too
I am going to mention in the plugin README that a version of `rpy2` < 3.0 is currently required

**Comment by jranke** [comment]
rpy2 v2 does not install on Debian bullseye any more (see my comment to #1135). Therefore I would like to reopen this issue, as wee need to make rmd_reader compatible with current rpy2 at some point.

**Comment by justinmayer** [comment]
Since the PR in question has just been merged, I believe this issue can remain closed. 😊

**Comment by jranke** [comment]
Yes, sure, thanks for your quick action on this!
