### ISSUE TITLE
[neighbors] RuntimeError: generator raised StopIteration

### ISSUE THREAD

**Issue by jorgesumle** [getpelican/pelican-plugins#1160]
See https://github.com/getpelican/pelican/issues/2597

It only happens with GitLab CI tests, see the relevant traceback [from test](https://gitlab.com/Freak-Spot/Freak-Spot/-/jobs/258941237):
```
Traceback (most recent call last):
  File "/builds/Freak-Spot/Freak-Spot/plugins/neighbors/neighbors.py", line 14, in iter3
    cur = next(it)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/pelican", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/pelican/__init__.py", line 631, in main
    pelican.run()
  File "/usr/local/lib/python3.7/dist-packages/pelican/__init__.py", line 194, in run
    writer = self.get_writer()
  File "/usr/local/lib/python3.7/dist-packages/pelican/__init__.py", line 268, in get_writer
    writers = [w for (_, w) in signals.get_writer.send(self)
  File "/usr/local/lib/python3.7/dist-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.7/dist-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/builds/Freak-Spot/Freak-Spot/plugins/i18n_subsites/i18n_subsites.py", line 436, in create_next_subsite
    new_pelican_obj.run()
  File "/usr/local/lib/python3.7/dist-packages/pelican/__init__.py", line 186, in run
    p.generate_context()
  File "/usr/local/lib/python3.7/dist-packages/pelican/generators.py", line 685, in generate_context
    signals.article_generator_finalized.send(self)
  File "/usr/local/lib/python3.7/dist-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.7/dist-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/builds/Freak-Spot/Freak-Spot/plugins/neighbors/neighbors.py", line 42, in neighbors
    set_neighbors(generator.articles, 'next_article', 'prev_article')
  File "/builds/Freak-Spot/Freak-Spot/plugins/neighbors/neighbors.py", line 29, in set_neighbors
    for nxt, cur, prv in iter3(articles):
RuntimeError: generator raised StopIteration
```

**Comment by Lucas-C** [comment]
I don't have Python 3.7 to test this, but I added some unit tests in https://github.com/getpelican/pelican-plugins/pull/1184 that should help debug this. Once Travis CI is enabled it will hopefully reproduce your issue
