### ISSUE TITLE
[custom_article_urls] Fails: can't get source path

### ISSUE THREAD

**Issue by GiovanH** [getpelican/pelican-plugins#1272]
The entire plugin fails whenever it matches a category because the `Article` doesn't know its own source path.

Example output for command `pelican content -o putput -s pelicanconf.py --verbose --debug`:

```
  | AttributeError: 'NoneType' object has no attribute 'lstrip'
  |___
  | Traceback (most recent call last):
  |   File "c:\users\seth\appdata\local\programs\python\python38-32\lib\site-packages\pelican\generators.py", line 618, in generate_context
  |     article = self.readers.read_file(
  |   File "c:\users\seth\appdata\local\programs\python\python38-32\lib\site-packages\pelican\readers.py", line 636, in read_file
  |     context_signal.send(context_sender, metadata=metadata)
  |   File "c:\users\seth\appdata\local\programs\python\python38-32\lib\site-packages\blinker\base.py", line 266, in send
  |     return [(receiver, receiver(sender, **kwargs))
  |   File "c:\users\seth\appdata\local\programs\python\python38-32\lib\site-packages\blinker\base.py", line 266, in <listcomp>
  |     return [(receiver, receiver(sender, **kwargs))
  |   File "C:\Users\Seth\Projects\Blog\pelican-test\pelican-plugins.git\custom_article_urls\custom_article_urls.py", line 44, in custom_url
  |     url = url_format.format(**temp_article.url_format)
  |   File "c:\users\seth\appdata\local\programs\python\python38-32\lib\site-packages\pelican\contents.py", line 213, in url_format
  |     'path': path_to_url(path),
  |   File "c:\users\seth\appdata\local\programs\python\python38-32\lib\site-packages\pelican\utils.py", line 436, in path_to_url
  |     return '/'.join(split_all(path))
  |   File "c:\users\seth\appdata\local\programs\python\python38-32\lib\site-packages\pelican\utils.py", line 877, in split_all
  |     path = path.lstrip('/')
  | AttributeError: 'NoneType' object has no attribute 'lstrip'
```

The problem seems to be that `path_to_url(path)` is fed a `None` value that comes from `get_relative_source_path`.

**Comment by GiovanH** [comment]
Actually, the subfolder is definitely NOT the issue here. Still sorting out what the problem is, but that's a dead end.

**Comment by GiovanH** [comment]
In `get_relative_source_path`, there's the following code block:
```python
        if not source_path:
            source_path = self.source_path
        if source_path is None:
            return None
```
`self.source_path` always seems to be `None`, so the function returns `None`, which breaks `path_to_url`.

**Comment by GiovanH** [comment]
To make matters worse, this bug is platform-dependent, because `path_to_url`, the function that actually throws the error, is implemented like this:
```python3
def path_to_url(path):
    """Return the URL corresponding to a given path."""
    if os.sep == '/':
        return path
    else:
        return '/'.join(split_all(path))
```
This happily passes `None` through on unix systems.

**Comment by GiovanH** [comment]
This was actually a pelican bug that is fixed in the latest development version.
