### ISSUE TITLE
CRITICAL: generator raised StopIteration make: *** [Makefile:44: html] Error 1

### ISSUE THREAD

**Issue by DanteAlighierin** [getpelican/pelican-plugins#1323]
I am trying to generate html pages using: 

``` bash
make html

```

And I get the following :

```bash

CRITICAL: generator raised StopIteration
make: *** [Makefile:44: html] Error 1

```

The Makefile on line 44 contains the following:

```makefile

html:
        $(PELICAN) $(INPUTDIR) -o $(OUTPUTDIR) -s $(CONFFILE) $(PELICANOPTS)

```

I suppose that the error is not in the config, but in the generator itself, right?

**Comment by avaris** [comment]
Can you show the full error when you run this:
```
DEBUG=1 make html
```

**Comment by DanteAlighierin** [comment]
```

CRITICAL: generator raised StopIteration
Traceback (most recent call last):
  File "/home/dante/blog/bob/pelican-plugins/neighbors/neighbors.py", line 14, in iter3
    cur = next(it)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/bin/pelican", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/pelican/__init__.py", line 512, in main
    pelican.run()
  File "/usr/lib/python3.9/site-packages/pelican/__init__.py", line 109, in run
    p.generate_context()
  File "/usr/lib/python3.9/site-packages/pelican/generators.py", line 682, in generate_context
    signals.article_generator_finalized.send(self)
  File "/usr/lib/python3.9/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/usr/lib/python3.9/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/home/dante/blog/bob/pelican-plugins/neighbors/neighbors.py", line 42, in neighbors
    set_neighbors(generator.articles, 'next_article', 'prev_article')
  File "/home/dante/blog/bob/pelican-plugins/neighbors/neighbors.py", line 29, in set_neighbors
    for nxt, cur, prv in iter3(articles):
RuntimeError: generator raised StopIteration
make: *** [Makefile:44: html] Error 1

```

**Comment by avaris** [comment]
This was fixed, your `neighbors` plugin is outdated. It's also [converted](https://github.com/pelican-plugins/neighbors) into new plugin format. You might want to update.

**Comment by DanteAlighierin** [comment]
thanks you, @avaris
