### ISSUE TITLE
[Migration] photos

### ISSUE THREAD

**Issue by phibos** [getpelican/pelican-plugins#1342]
I'm not the original author of the photos plugin, but I would like to migrate it to the new organisation and provide some improvements.

**Comment by phibos** [comment]
I'm currently migrating the repo. Feel free to have a look at https://github.com/phibos/pelican-photos . Hope this helps. Not finished yet, some tests still fail.

**Comment by phibos** [comment]
All issues have been fixed and an admin can push the repository into the new pelican-plugins group.

@justinmayer

**Comment by phibos** [comment]
I have also created a PR to mark the photos plugin as migrated.

@justinmayer

**Comment by phibos** [comment]
Anything I can do to speed up the process? @MinchinWeb @kernc @kdeldycke @davidlesieur

**Comment by justinmayer** [comment]
Hi @phibos. Thank you for the offer to assist with the Photos plugin migration. I have many other high-priority items competing for my attention at this time, but I rest assured I will follow up with you as soon as I can. Have a great day! 😁

**Comment by paulo-coutinho** [comment]
Hi,

I have erros with photos plugin:

```
DEBUG: Pelican version: 4.6.0
DEBUG: Python version: 3.9.5
DEBUG: Adding current directory to system path
DEBUG: Finding namespace plugins
DEBUG: Namespace plugins found:
  | pelican.plugins.webassets
DEBUG: Loading plugin `assets`
DEBUG: Loading plugin `sitemap`
DEBUG: Loading plugin `summary`
DEBUG: Loading plugin `extended_meta`
DEBUG: Loading plugin `related_posts`
DEBUG: Loading plugin `photos`
DEBUG: piexif found.
DEBUG: Registering plugin `assets`
DEBUG: Registering plugin `sitemap`
DEBUG: Registering plugin `summary`
DEBUG: Registering plugin `extended_meta`
DEBUG: Registering plugin `related_posts`
DEBUG: Registering plugin `photos`
  --- AutoReload Mode: Monitoring `content`, `theme` and `settings` for changes. ---

Serving site at: http://127.0.0.1:8000 - Tap CTRL-C to stop

-> Modified: settings, content, theme, [static]images, [static]extras. re-generating...
Process SpawnPoolWorker-1:1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/queues.py", line 368, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'photos'
```

**Comment by phibos** [comment]
I'm sorry, but I'm unable to reproduce the error with the given information.

Install pelican
```
cd /tmp
mkdir pelican_test
cd pelican_test
python -m venv venv
source venv/bin/activate
pip install pelican
pip install markdown
pelican-quickstart
```

Install plugin
```
cd /tmp/
git clone git@github.com:phibos/pelican-photos.git
cd pelican-photos
git checkout migrate
source /tmp/pelican_test/venv/bin/activate
pip install .
```
Files
```python
$ cat pelicanconf.py 
#!/usr/bin/env python
# -*- coding: utf-8 -*- #

AUTHOR = 'Author'
SITENAME = 'Test'
SITEURL = ''

PATH = 'content'

TIMEZONE = 'Europe/Paris'

DEFAULT_LANG = 'en'

# Feed generation is usually not desired when developing
FEED_ALL_ATOM = None
CATEGORY_FEED_ATOM = None
TRANSLATION_FEED_ATOM = None
AUTHOR_FEED_ATOM = None
AUTHOR_FEED_RSS = None

PLUGINS = ['photos']

PHOTO_LIBRARY = "content/gallery"

# Blogroll
LINKS = (('Pelican', 'https://getpelican.com/'),
         ('Python.org', 'https://www.python.org/'),
         ('Jinja2', 'https://palletsprojects.com/p/jinja/'),
         ('You can modify those links in your config file', '#'),)

# Social widget
SOCIAL = (('You can add links in your config file', '#'),
          ('Another social link', '#'),)

DEFAULT_PAGINATION = 10

# Uncomment following line if you want document-relative URLs when developing
#RELATIVE_URLS = True
```
```markdown
$ cat content/test.md 
Title: Test
Date: 2021-01-01
Image: {photo}foo/test.jpg
Gallery: {photo}foo

Foo
```

```
$ file content/gallery/foo/test.jpg 
content/gallery/foo/test.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 1600x4780, components 3
```

```
$ DEBUG=1 make html
"pelican" "/tmp/pelican_test/content" -o "/tmp/pelican_test/output" -s "/tmp/pelican_test/pelicanconf.py" -D
DEBUG: Pelican version: 4.6.0
DEBUG: Python version: 3.9.6
WARNING: Locale could not be set. Check the LOCALE setting, ensuring it is valid and available on your system.
DEBUG: Adding current directory to system path
DEBUG: Finding namespace plugins
DEBUG: piexif found.
DEBUG: Namespace plugins found:
  | pelican.plugins.photos
DEBUG: Loading plugin `photos`
DEBUG: Registering plugin `pelican.plugins.photos`
WARNING: Watched path does not exist: /tmp/pelican_test/content/images
DEBUG: Found generator: ArticlesGenerator (internal)
DEBUG: Found generator: PagesGenerator (internal)
DEBUG: Found generator: StaticGenerator (internal)
DEBUG: Template list: ['!simple/archives.html', '!simple/article.html', '!simple/author.html', '!simple/authors.html', '!simple/base.html', '!simple/categories.html', '!simple/category.html', '!simple/gosquared.html', '!simple/index.html', '!simple/page.html', '!simple/pagination.html', '!simple/period_archives.html', '!simple/tag.html', '!simple/tags.html', '!simple/translations.html', '!theme/analytics.html', '!theme/archives.html', '!theme/article.html', '!theme/article_infos.html', '!theme/author.html', '!theme/authors.html', '!theme/base.html', '!theme/category.html', '!theme/comments.html', '!theme/disqus_script.html', '!theme/github.html', '!theme/index.html', '!theme/page.html', '!theme/period_archives.html', '!theme/tag.html', '!theme/taglist.html', '!theme/tags.html', '!theme/translations.html', '!theme/twitter.html', 'analytics.html', 'archives.html', 'article.html', 'article_infos.html', 'author.html', 'authors.html', 'base.html', 'categories.html', 'category.html', 'comments.html', 'disqus_script.html', 'github.html', 'gosquared.html', 'index.html', 'page.html', 'pagination.html', 'period_archives.html', 'tag.html', 'taglist.html', 'tags.html', 'translations.html', 'twitter.html']
DEBUG: Read file test.md -> Article
DEBUG: Signal article_generator_preread.send(ArticlesGenerator)
DEBUG: Successfully imported extension module "markdown.extensions.codehilite".
DEBUG: Successfully loaded extension "markdown.extensions.codehilite.CodeHiliteExtension".
DEBUG: Successfully imported extension module "markdown.extensions.extra".
DEBUG: Successfully loaded extension "markdown.extensions.fenced_code.FencedCodeExtension".
DEBUG: Successfully loaded extension "markdown.extensions.footnotes.FootnoteExtension".
DEBUG: Successfully loaded extension "markdown.extensions.attr_list.AttrListExtension".
DEBUG: Successfully loaded extension "markdown.extensions.def_list.DefListExtension".
DEBUG: Successfully loaded extension "markdown.extensions.tables.TableExtension".
DEBUG: Successfully loaded extension "markdown.extensions.abbr.AbbrExtension".
DEBUG: Successfully loaded extension "markdown.extensions.md_in_html.MarkdownInHtmlExtension".
DEBUG: Successfully loaded extension "markdown.extensions.extra.ExtraExtension".
DEBUG: Successfully imported extension module "markdown.extensions.meta".
DEBUG: Successfully loaded extension "markdown.extensions.meta.MetaExtension".
DEBUG: Signal article_generator_context.send(ArticlesGenerator, <metadata>)
-> photos: Gallery detected: foo
-> photos: No EXIF for gallery at file content/gallery/foo/exif.txt
DEBUG: read_notes issue: photos: No EXIF for gallery at file content/gallery/foo/exif.txt. Debug message:[Errno 2] No such file or directory: 'content/gallery/foo/exif.txt'
-> photos: No captions for gallery at file content/gallery/foo/captions.txt
DEBUG: read_notes issue: photos: No captions for gallery at file content/gallery/foo/captions.txt. Debug message:[Errno 2] No such file or directory: 'content/gallery/foo/captions.txt'
-> photos: No blacklist for gallery at file content/gallery/foo/blacklist.txt
DEBUG: read_notes issue: photos: No blacklist for gallery at file content/gallery/foo/blacklist.txt. Debug message:[Errno 2] No such file or directory: 'content/gallery/foo/blacklist.txt'
DEBUG: Gallery Data: [('', [('test.jpg', 'photos/foo/test.jpg', 'photos/foo/testt.jpg', '', '')])]
-> Writing /tmp/pelican_test/output/test.html
-> Writing /tmp/pelican_test/output/index.html
-> Writing /tmp/pelican_test/output/tags.html
-> Writing /tmp/pelican_test/output/categories.html
-> Writing /tmp/pelican_test/output/authors.html
-> Writing /tmp/pelican_test/output/archives.html
-> Writing /tmp/pelican_test/output/category/misc.html
-> Writing /tmp/pelican_test/output/author/author.html
DEBUG: Debug Status: False
-> photos: make photo content/gallery/foo/test.jpg -> /tmp/pelican_test/output/photos/foo/testa.jpg
-> photos: make photo content/gallery/foo/test.jpg -> /tmp/pelican_test/output/photos/foo/testt.jpg
DEBUG: Directory already exists at /tmp/pelican_test/output/photos/foo
-> photos: make photo content/gallery/foo/test.jpg -> /tmp/pelican_test/output/photos/foo/test.jpg
-> Creating directory /tmp/pelican_test/output/theme
-> Creating directory /tmp/pelican_test/output/theme/images
-> Creating directory /tmp/pelican_test/output/theme/images/icons
[...]
```

**Comment by phibos** [comment]
@justinmayer looks like you didn't have the time to migrate the photos plugin. Is there someone else who can assist?

Would be great if someone could just help to migrate all the requested plugins and the community can go on with maintaining them.

**Comment by justinmayer** [comment]
@phibos: I pushed the legacy commits to the new repository and invited you to join it: https://github.com/pelican-plugins/photos

Would you please submit your changes as a PR to that repository? Thank you! 😊

**Comment by justinmayer** [comment]
@phibos: I went ahead and added your changes to the [`migrate`](https://github.com/pelican-plugins/photos/tree/migrate) branch here. Any comments before I merge that branch and publish its contents to PyPI?

**Comment by phibos** [comment]
@justinmayer Thanks for creating the project in the new organisation. From my point of view the code can be published.

**Comment by justinmayer** [comment]
Thank you, @phibos, for all your help with the migration. Version 1.0 of the newly migrated namespace plugin has been published to PyPI.

**Comment by phibos** [comment]
Thanks @justinmayer
