### ISSUE TITLE
feed_summary not working in Python 3

### ISSUE THREAD

**Issue by mtirsel** [getpelican/pelican-plugins#291]
types.ClassType is no more in Python 3:

```
Traceback (most recent call last):
    File "/home/bruce/.venvs/blogging/bin/pelican", line 9, in <module>
      load_entry_point('pelican==3.4.0', 'console_scripts', 'pelican')()
    File "/home/bruce/.venvs/blogging/lib/python3.3/site-packages/pelican/__init__.py", line 344, in main
      pelican, settings = get_instance(args)
    File "/home/bruce/.venvs/blogging/lib/python3.3/site-packages/pelican/__init__.py", line 338, in get_instance
      return cls(settings), settings
    File "/home/bruce/.venvs/blogging/lib/python3.3/site-packages/pelican/__init__.py", line 57, in __init__
      signals.initialized.send(self)
    File "/home/bruce/.venvs/blogging/lib/python3.3/site-packages/blinker/base.py", line 267, in send
      for receiver in self.receivers_for(sender)]
    File "/home/bruce/.venvs/blogging/lib/python3.3/site-packages/blinker/base.py", line 267, in <listcomp>
      for receiver in self.receivers_for(sender)]
    File "/home/bruce/Projects/blogging/plugins/feed_summary/feed_summary.py", line 51, in patch_pelican_writer
      @magic_set(pelican_object)
    File "/home/bruce/Projects/blogging/plugins/feed_summary/magic_set.py", line 56, in decorator
      or isinstance(obj, types.ClassType))
AttributeError: 'module' object has no attribute 'ClassType'
```

**Comment by justinmayer** [comment]
Not sure if this is still a problem. If so, please feel free to comment here so the issue can be re-opened.
