### ISSUE TITLE
Assets: SASS\Compass works before theme is copied to output dir

### ISSUE THREAD

**Issue by Shaked** [getpelican/pelican-plugins#370]
Hey, 

So after "investigating" an issue regarding Pelican, Assets and Compass (sprites), it seems that up until now Compass searched the relative folders using the _OUTPUT_PATH/THEME/PATH/TO/IMGS_. As a result of the static generator changes, this seems to stop working. When turning off _DELETE_OUTPUT_DIRECTORY_ and copying manually the img folder, it works perfect as before. Any idea how this can be solved ? Hope I was clear, thanks.

P.S I have tried to Google for quite some time plus asked on the IRC channel but couldn't find any solution. 

```
Compass 1.0.1 (Polaris)
Sass 3.4.9 (Selective Steve)
Python 2.7.8
pelican --version: 3.5.0
PLUGINS = ['pelican_gist', 'assets', 'related_posts', 'sitemap', 'pin_to_top'] 
Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64
```

Edit (forgot to attach the error): 

```
Shaked@mac shakedosblog (master) $ Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/usr/local/lib/python2.7/site-packages/pelican/log.py", line 25, in format
    record.msg = record.msg.replace('\n', '\n  | ')
AttributeError: 'tuple' object has no attribute 'replace'
Logged from file __init__.py, line 410
CRITICAL: compass: subprocess had error: stderr=, stdout=    error /Users/Shaked/Projects/shakedosblog/themes/shakedos/pre-static/scss/base.scss (Line 2: No files were found in the load path matching "img/btn-icons/*.png". Your current load paths are: /Users/Shaked/Projects/shakedosblog/output/theme)
Compilation failed in 1 files.
, returncode=1
Traceback (most recent call last):
  File "/usr/local/bin/pelican", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/pelican/__init__.py", line 400, in main
    pelican.run()
  File "/usr/local/lib/python2.7/site-packages/pelican/__init__.py", line 175, in run
    p.generate_output(writer)
  File "/usr/local/lib/python2.7/site-packages/pelican/generators.py", line 600, in generate_output
    self.generate_pages(writer)
  File "/usr/local/lib/python2.7/site-packages/pelican/generators.py", line 475, in generate_pages
    self.generate_articles(write)
  File "/usr/local/lib/python2.7/site-packages/pelican/generators.py", line 353, in generate_articles
    override_output=hasattr(article, 'override_save_as'))
  File "/usr/local/lib/python2.7/site-packages/pelican/writers.py", line 212, in write_file
    override_output)
  File "/usr/local/lib/python2.7/site-packages/pelican/writers.py", line 156, in _write_file
    output = template.render(localcontext)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Shaked/Projects/shakedosblog/themes/shakedos/templates/article.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/Shaked/Projects/shakedosblog/themes/shakedos/templates/base.html", line 15, in top-level template code
    {% assets filters="compass,yui_css", output="css/shakedos.min.css",PRE_STATIC ~ "/bower_components/sass-bootstrap/lib/bootstrap.scss", PRE_STATIC ~ "/scss/base.scss",PRE_STATIC ~ "/scss/index.scss" %}
  File "/usr/local/lib/python2.7/site-packages/webassets/ext/jinja2.py", line 186, in _render_assets
    urls = bundle.urls()
  File "/usr/local/lib/python2.7/site-packages/webassets/bundle.py", line 787, in urls
    urls.extend(bundle._urls(new_ctx, extra_filters, *args, **kwargs))
  File "/usr/local/lib/python2.7/site-packages/webassets/bundle.py", line 746, in _urls
    *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/webassets/bundle.py", line 600, in _build
    force, disable_cache=disable_cache, extra_filters=extra_filters)
  File "/usr/local/lib/python2.7/site-packages/webassets/bundle.py", line 506, in _merge_and_apply
    cache_key=[FileHunk(cnt)] if not is_url(cnt) else [])
  File "/usr/local/lib/python2.7/site-packages/webassets/merge.py", line 322, in apply_func
    return self._wrap_cache(key, func)
  File "/usr/local/lib/python2.7/site-packages/webassets/merge.py", line 219, in _wrap_cache
    content = func().getvalue()
  File "/usr/local/lib/python2.7/site-packages/webassets/merge.py", line 313, in func
    getattr(filter, type)(out, *args, **kwargs_final)
  File "/usr/local/lib/python2.7/site-packages/webassets/filter/compass.py", line 232, in open
    stderr, stdout, proc.returncode))
webassets.exceptions.FilterError: compass: subprocess had error: stderr=, stdout=    error /Users/Shaked/Projects/shakedosblog/themes/shakedos/pre-static/scss/base.scss (Line 2: No files were found in the load path matching "img/btn-icons/*.png". Your current load paths are: /Users/Shaked/Projects/shakedosblog/output/theme)
Compilation failed in 1 files.
, returncode=1
```

Thank you, 
Shaked

**Comment by justinmayer** [comment]
Glad you found a workaround.
