### ISSUE TITLE
unicode in liquid_tags.video

### ISSUE THREAD

**Issue by MafiaInc** [getpelican/pelican-plugins#560]
I have and issue I couldn't resolved. I have some video files with unicode characters in filename. I'm adding a video liquid_tag like this:

{% video {filename}/img/2015/02/Сурва-Перник-2015.webm 607 240 /img/2015/02/Сурва-Перник-2015.jpg %}

Then I'm getting the following error:

``` python
ERROR: Could not process ./сурва-фестивалът.md
  | UnicodeEncodeError: 'ascii' codec can't encode characters in position 13-17: ordinal not in range(128)
  |___
  | Traceback (most recent call last):
  |   File "/usr/local/lib/python2.7/site-packages/pelican/generators.py", line 514, in generate_context
  |     context_sender=self)
  |   File "/usr/local/lib/python2.7/site-packages/pelican/readers.py", line 508, in read_file
  |     content, reader_metadata = reader.read(path)
  |   File "/usr/local/lib/python2.7/site-packages/pelican/readers.py", line 287, in read
  |     content = self._md.convert(text)
  |   File "/usr/local/lib/python2.7/site-packages/markdown/__init__.py", line 368, in convert
  |     self.lines = prep.run(self.lines)
  |   File "/usr/local/www/kamen-pelican/plugins/liquid_tags/mdx_liquid_tags.py", line 44, in run
  |     liquid_tags[i] = self._tags[tag](self, tag, markup.strip())
  |   File "/usr/local/www/kamen-pelican/plugins/liquid_tags/video.py", line 55, in video
  |     """.format(width=width, height=height, poster=poster).strip()
  | UnicodeEncodeError: 'ascii' codec can't encode characters in position 13-17: ordinal not in range(128)
```

I tried adding .decode('utf-8') on some places in the code were I suspected is the right place to do, but I couldn't manage to resolve it. Temporary I'm renaming my file to ascii characters only.

Can someone help?

**Comment by justinmayer** [comment]
Not sure if this is still a problem. If so, please feel free to comment here so the issue can be re-opened.
