### ISSUE TITLE
liquid_tags decode str error

### ISSUE THREAD

**Issue by ntimeu** [getpelican/pelican-plugins#602]
Since commit 3f5c07585be36a83f45582d80b1681feff120cab (and later), Python3.4 raise an error when trying to include code (using liquid_tags) :

``` bash
% pelican content -s publishconf.py
ERROR: Could not process ./my-post.md
  | AttributeError: 'str' object has no attribute 'decode'
```

When using the -D flag to pelican, I got the following error (output cut for readability)

``` bash
% pelican -D content -s publishconf.py
ERROR: Could not process ./my-post.md
  | AttributeError: 'str' object has no attribute 'decode'
  |___
  | Traceback (most recent call last):
  |   File "/home/cxxwaves/.pve/pelican/lib/python3.4/site-packages/pelican/generators.py", line 514, in generate_context
  |     context_sender=self)
  |   File "/home/cxxwaves/.pve/pelican/lib/python3.4/site-packages/pelican/readers.py", line 508, in read_file
  |     content, reader_metadata = reader.read(path)
  |   File "/home/cxxwaves/.pve/pelican/lib/python3.4/site-packages/pelican/readers.py", line 287, in read
  |     content = self._md.convert(text)
  |   File "/home/cxxwaves/.pve/pelican/lib/python3.4/site-packages/markdown/__init__.py", line 368, in convert
  |     self.lines = prep.run(self.lines)
  |   File "/home/cxxwaves/gites/blog/pelican-plugins/liquid_tags/mdx_liquid_tags.py", line 48, in run
  |     liquid_tags[i] = self._tags[tag](self, tag, markup.strip())
  |   File "/home/cxxwaves/gites/blog/pelican-plugins/liquid_tags/include_code.py", line 131, in include_code
  |     + close_tag + '\n')
  | AttributeError: 'str' object has no attribute 'decode
```

It seems that at line 130 of file include_code.py, python3.4 can't call .decode(codec) on a str. Removing it correct the issue but I don't think this is the best idea.

Do you have any workaround for python3 ?

**Comment by ozmoroz** [comment]
Same here.
