### ISSUE TITLE
Textile plugin 'bool' object is not callable

### ISSUE THREAD

**Issue by golfecholima** [getpelican/pelican-plugins#709]
_Updated w/ more details_

I get the following when trying to process a textile file ...

```
ERROR: Could not process ./test.textile
  | TypeError: 'bool' object is not callable
```

Debug log:

```
DEBUG: Adding current directory to system path
DEBUG: Temporarily adding PLUGIN_PATHS to system path
DEBUG: Loading plugin `textile_reader`
DEBUG: Registering plugin `textile_reader`
DEBUG: Restoring system path
DEBUG: Missing dependencies for textile
  --- AutoReload Mode: Monitoring `content`, `theme` and `settings` for changes. ---

-> Modified: content, theme, settings. re-generating...
DEBUG: Template list: [u'!simple/archives.html', u'!simple/article.html', u'!simple/author.html', u'!simple/authors.html', u'!simple/base.html', u'!simple/categories.html', u'!simple/category.html', u'!simple/gosquared.html', u'!simple/index.html', u'!simple/page.html', u'!simple/pagination.html', u'!simple/period_archives.html', u'!simple/tag.html', u'!simple/tags.html', u'!simple/translations.html', u'archives.html', u'article.html', u'author.html', u'authors.html', u'base.html', u'categories.html', u'category.html', u'gosquared.html', u'index.html', u'page.html', u'pagination.html', u'period_archives.html', u'photoarticle.html', u'photoroll.html', u'tag.html', u'tags.html', u'translations.html']
DEBUG: Read file helloworld.md -> Article
DEBUG: Signal article_generator_preread.send(ArticlesGenerator)
DEBUG: Successfuly imported extension module "markdown.extensions.codehilite".
DEBUG: Successfully loaded extension "markdown.extensions.codehilite.CodeHiliteExtension".
DEBUG: Successfuly imported extension module "markdown.extensions.extra".
DEBUG: Successfuly imported extension module "markdown.extensions.smart_strong".
DEBUG: Successfully loaded extension "markdown.extensions.smart_strong.SmartEmphasisExtension".
DEBUG: Successfuly imported extension module "markdown.extensions.fenced_code".
DEBUG: Successfully loaded extension "markdown.extensions.fenced_code.FencedCodeExtension".
DEBUG: Successfuly imported extension module "markdown.extensions.footnotes".
DEBUG: Successfully loaded extension "markdown.extensions.footnotes.FootnoteExtension".
DEBUG: Successfuly imported extension module "markdown.extensions.attr_list".
DEBUG: Successfully loaded extension "markdown.extensions.attr_list.AttrListExtension".
DEBUG: Successfuly imported extension module "markdown.extensions.def_list".
DEBUG: Successfully loaded extension "markdown.extensions.def_list.DefListExtension".
DEBUG: Successfuly imported extension module "markdown.extensions.tables".
DEBUG: Successfully loaded extension "markdown.extensions.tables.TableExtension".
DEBUG: Successfuly imported extension module "markdown.extensions.abbr".
DEBUG: Successfully loaded extension "markdown.extensions.abbr.AbbrExtension".
DEBUG: Successfully loaded extension "markdown.extensions.extra.ExtraExtension".
DEBUG: Successfuly imported extension module "markdown.extensions.meta".
DEBUG: Successfully loaded extension "markdown.extensions.meta.MetaExtension".
DEBUG: Signal article_generator_context.send(ArticlesGenerator, <metadata>)
DEBUG: Read file template.md -> Article
ERROR: Unknown status 'hidden' for file ./template.md, skipping it.
DEBUG: Read file test.textile -> Article
ERROR: Could not process ./test.textile
  | TypeError: 'bool' object is not callable
  |___
  | Traceback (most recent call last):
  |   File "/Users/george/Documents/repos/virtualenvs/pelican/lib/python2.7/site-packages/pelican/generators.py", line 514, in generate_context
  |     context_sender=self)
  |   File "/Users/george/Documents/repos/virtualenvs/pelican/lib/python2.7/site-packages/pelican/readers.py", line 508, in read_file
  |     content, reader_metadata = reader.read(path)
  |   File "/Users/george/Documents/repos/virtualenvs/pelican/bygeorge/pelican-plugins/textile_reader/textile_reader.py", line 59, in read
  |     metadata = self._parse_metadata(headerdict)
  |   File "/Users/george/Documents/repos/virtualenvs/pelican/bygeorge/pelican-plugins/textile_reader/textile_reader.py", line 44, in _parse_metadata
  |     value == textile(value)
  | TypeError: 'bool' object is not callable
DEBUG: Read file pages/404.md -> Page
DEBUG: Signal page_generator_preread.send(PagesGenerator)
DEBUG: Signal page_generator_context.send(PagesGenerator, <metadata>)
DEBUG: Read file pages/about.md -> Page
DEBUG: Read file pages/contact.md -> Page
```

I have both pillow and regex installed. Used `pip` to install textile. Not sure what other dependencies there are.

@joey-coleman, any ideas?

**Comment by joey-coleman** [comment]
No ideas offhand, sorry — I originally wrote that some 3 years ago, so I wonder if anything has changed with the python textile processor since then.  On a guess, I would have been using version 2.1.6; you probably have the latest (2.2.2) installed.  Perhaps `pip install -U textile==2.1.6` would work (but no guarantees).

**Comment by justinmayer** [comment]
Closing due to inactivity. Please feel free to comment here if you feel the issue should be re-opened.

**Comment by tewhalen** [comment]
Noting for the record that this error is generated if the textile library isn't installed. Rather than this resulting in the plugin being marked as disabled, it silently replaces textile with False.

```
try:
    from textile import textile
except ImportError:
    textile = False
```
