### ISSUE TITLE
Unicode errors using bootstrap2 template and w3c_validate plugin

### ISSUE THREAD

**Issue by dpetzel** [getpelican/pelican-plugins#75]
I'm really new to pelican, but I'm stuck trying to use the 3wc_validate plugin. If I omit the plugin everything works fine, however when I enable the plugin, I get the following error when running `make html`

```
-> writing /home/user/git/user/user.info/output/archives.html
-> writing /home/user/git/user/user.info/output/pages/about-me.html
-> Validating: /home/user/git/user/user.info/output/archives.html
CRITICAL: File name or file only. Got <type 'unicode'> instead
Traceback (most recent call last):
  File "/home/user/virtualenvs/pelican/bin/pelican", line 9, in <module>
    load_entry_point('pelican==3.2.2', 'console_scripts', 'pelican')()
  File "/home/user/virtualenvs/pelican/local/lib/python2.7/site-packages/pelican/__init__.py", line 378, in main
    pelican.run()
  File "/home/user/virtualenvs/pelican/local/lib/python2.7/site-packages/pelican/__init__.py", line 183, in run
    signals.finalized.send(self)
  File "/home/user/virtualenvs/pelican/local/lib/python2.7/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/home/user/git/user/user.info/pelican-plugins/w3c_validate/wc3_validate.py", line 25, in validate_files
    validate(filepath)
  File "/home/user/git/user/user.info/pelican-plugins/w3c_validate/wc3_validate.py", line 42, in validate
    vld.validate_file(filename)
  File "/home/user/virtualenvs/pelican/local/lib/python2.7/site-packages/py_w3c/validators/html/validator.py", line 67, in validate_file
    raise Exception("File name or file only. Got %s instead" % type(filename_or_file))
Exception: File name or file only. Got <type 'unicode'> instead
make: *** [/home/user/git/user/user.info/output/index.html] Error 1
```

**Comment by justinmayer** [comment]
Not sure if this is still a problem. If so, please feel free to comment here so the issue can be re-opened.
