### ISSUE TITLE
[better_figures_and_images] invalid syntax

### ISSUE THREAD

**Issue by microniko** [getpelican/pelican-plugins#804]
If `better_figures_and_images` plugin is active, I have this error :

```
$ pelican
Traceback (most recent call last):
  File "/home/nicolas/python/envvirt/pelican/bin/pelican", line 11, in <module>
    sys.exit(main())
  File "/home/nicolas/python/envvirt/pelican/lib/python3.5/site-packages/pelican/__init__.py", line 386, in main
    pelican, settings = get_instance(args)
  File "/home/nicolas/python/envvirt/pelican/lib/python3.5/site-packages/pelican/__init__.py", line 380, in get_instance
    return cls(settings), settings
  File "/home/nicolas/python/envvirt/pelican/lib/python3.5/site-packages/pelican/__init__.py", line 57, in __init__
    self.init_plugins()
  File "/home/nicolas/python/envvirt/pelican/lib/python3.5/site-packages/pelican/__init__.py", line 77, in init_plugins
    str('module'))
  File "/home/nicolas/sites/www/pelican-plugins/better_figures_and_images/__init__.py", line 1, in <module>
    from .better_figures_and_images import *
  File "/home/nicolas/sites/www/pelican-plugins/better_figures_and_images/better_figures_and_images.py", line 24, in <module>
    import pysvg.parser
  File "/home/nicolas/python/envvirt/pelican/lib/python3.5/site-packages/pysvg/parser.py", line 32
    print calculateMethodName(attr)+' not found in:'+obj._elementName
                            ^   
SyntaxError: invalid syntax
```

Thx

**Comment by avaris** [comment]
Looks like the recent addition (#779) included a new dependency (`pysvg`) and it's not Python3 compatible. 
cc: @ohporter

**Comment by jar1karp** [comment]
One solution is to extract the python3 patch from [Fedora SRPM](http://koji.fedoraproject.org/koji/buildinfo?buildID=783267) and have pip install the patched version of pysvg from source.

**Comment by JaniKarh** [comment]
Not the optimal solution, but managed to get it to work, like @jar1karp proposed. Can the Python 3 compatible version be found anywhere in GitHub atm? Might help a lot to publish the latest version to pypi.

**Comment by alorence** [comment]
I was also annoyed by this issue, so I tried to apply 2to3 to original pysvg code, and it worked. Just pushed the result on Pypi. You can install it from pip: pysvg-py3

More info: https://github.com/alorence/pysvg-py3
Pypi: https://pypi.python.org/pypi/pysvg-py3

**Comment by justinmayer** [comment]
Missing dependency has been added to the README via the linked PR.
