### ISSUE TITLE
Can't set attribute category.slug = slug

### ISSUE THREAD

**Issue by lum4chi** [getpelican/pelican-plugins#846]
Hello everyone, I'm experience this error:
> lum4chi@b00k:~/Projects/xxx$ DEBUG=1 make html
> pelican /Users/lum4chi/Projects/xxx/content -o /Users/lum4chi/Projects/xxx/output -s /Users/lum4chi/Projects/xxx/pelicanconf.py  -D
> DEBUG: Pelican version: 3.7.1
> DEBUG: Python version: 3.6.0
> DEBUG: Adding current directory to system path
> DEBUG: Temporarily adding PLUGIN_PATHS to system path
> DEBUG: Loading plugin `pelican-ipynb.markup`
> DEBUG: Registering plugin `pelican-ipynb.markup`
> DEBUG: Loading plugin `post_stats`
> DEBUG: Registering plugin `post_stats`
> DEBUG: Loading plugin `category_meta`
> DEBUG: Registering plugin `category_meta`
> DEBUG: Restoring system path
> DEBUG: Template list: ['!simple/archives.html', '!simple/article.html', '!simple/author.html', '!simple/authors.html', '!simple/base.html', '!simple/categories.html', '!simple/category.html', '!simple/gosquared.html', '!simple/index.html', '!simple/page.html', '!simple/pagination.html', '!simple/period_archives.html', '!simple/tag.html', '!simple/tags.html', '!simple/translations.html', 'archives.html', 'article.html', 'author.html', 'authors.html', 'base.html', 'categories.html', 'category.html', 'gosquared.html', 'include/analytics.html', 'include/comments.html', 'include/pagination.html', 'index.html', 'page.html', 'pagination.html', 'period_archives.html', 'sitemap.html', 'tag.html', 'tags.html', 'translations.html']
> DEBUG: Read file programmazione/euler_001.ipynb -> Article
> DEBUG: Signal article_generator_preread.send(ArticlesGenerator)
> DEBUG: Successfuly imported extension module "markdown.extensions.codehilite".
> DEBUG: Successfully loaded extension "markdown.extensions.codehilite.CodeHiliteExtension".
> DEBUG: Successfuly imported extension module "markdown.extensions.extra".
> DEBUG: Successfuly imported extension module "markdown.extensions.smart_strong".
> DEBUG: Successfully loaded extension "markdown.extensions.smart_strong.SmartEmphasisExtension".
> DEBUG: Successfuly imported extension module "markdown.extensions.fenced_code".
> DEBUG: Successfully loaded extension "markdown.extensions.fenced_code.FencedCodeExtension".
> DEBUG: Successfuly imported extension module "markdown.extensions.footnotes".
> DEBUG: Successfully loaded extension "markdown.extensions.footnotes.FootnoteExtension".
> DEBUG: Successfuly imported extension module "markdown.extensions.attr_list".
> DEBUG: Successfully loaded extension "markdown.extensions.attr_list.AttrListExtension".
> DEBUG: Successfuly imported extension module "markdown.extensions.def_list".
> DEBUG: Successfully loaded extension "markdown.extensions.def_list.DefListExtension".
> DEBUG: Successfuly imported extension module "markdown.extensions.tables".
> DEBUG: Successfully loaded extension "markdown.extensions.tables.TableExtension".
> DEBUG: Successfuly imported extension module "markdown.extensions.abbr".
> DEBUG: Successfully loaded extension "markdown.extensions.abbr.AbbrExtension".
> DEBUG: Successfully loaded extension "markdown.extensions.extra.ExtraExtension".
> DEBUG: Successfuly imported extension module "markdown.extensions.meta".
> DEBUG: Successfully loaded extension "markdown.extensions.meta.MetaExtension".
> DEBUG: Applying preprocessor: coalesce_streams
> DEBUG: Applying preprocessor: CSSHTMLHeaderPreprocessor
> DEBUG: Applying preprocessor: HighlightMagicsPreprocessor
> DEBUG: Attempting to load template basic.tpl
> DEBUG:     template_path: .
> DEBUG: Loaded template /usr/local/lib/python3.6/site-packages/nbconvert/exporters/../templates/html/basic.tpl
> DEBUG: Signal article_generator_context.send(ArticlesGenerator, <metadata>)
> DEBUG: Read file programmazione/index.md -> Article
> DEBUG: Read file programmazione/rosalind_DNA.ipynb -> Article
> DEBUG: Read file risorse/index.md -> Article
> DEBUG: Read file risorse/proj_euler.md -> Article
> DEBUG: Read file risorse/rosalind.md -> Article
> DEBUG: Read file risorse/tedtalks.md -> Article
> CRITICAL: AttributeError: can't set attribute
> Traceback (most recent call last):
>   File "/usr/local/bin/pelican", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.6/site-packages/pelican/__init__.py", line 487, in main
>     pelican.run()
>   File "/usr/local/lib/python3.6/site-packages/pelican/__init__.py", line 171, in run
>     p.generate_context()
>   File "/usr/local/lib/python3.6/site-packages/pelican/generators.py", line 566, in generate_context
>     signals.article_generator_pretaxonomy.send(self)
>   File "/usr/local/lib/python3.6/site-packages/blinker/base.py", line 267, in send
>     for receiver in self.receivers_for(sender)]
>   File "/usr/local/lib/python3.6/site-packages/blinker/base.py", line 267, in <listcomp>
>     for receiver in self.receivers_for(sender)]
>   File "/opt/pelican-plugins/category_meta/category_meta.py", line 106, in pretaxonomy_hook
>     make_category(article, os.path.basename(dirname))
>   File "/opt/pelican-plugins/category_meta/category_meta.py", line 73, in make_category
>     category.slug = slug
> AttributeError: can't set attribute
> make: *** [html] Error 1

I'm able to skip this simply by commenting line 73 ```category.slug = slug```.  Output seems correct. Hope this help someone!

**Comment by avaris** [comment]
Were you using an older version of pelican before?

**Comment by lum4chi** [comment]
I started my blog with pelican 3.6.something (don't remember) but I turn this plug on only after upgrading to 3.7.1

**Comment by avaris** [comment]
If you have a `cache` folder, try removing that. There were some changes to metadata objects like `Category` back in 3.6 (IIRC) that made them incompatible with the earlier versions. If you had cached objects from before that, it could cause some issues.

**Comment by lum4chi** [comment]
I'm sorry, do you mean ```output``` directory? I think to have missed some pelican lessons ^^'.
This maybe correlate with another warning that I have:
```WARNING: _get_summary() has been deprecated since 3.6.4. Use the summary decorator instead```

**Comment by avaris** [comment]
No, I meant `cache`, but nevermind... After digging into code a bit, I see the issue for your original question. This is a possible bug in pelican.
