### ISSUE TITLE
filetime_from_git fails when pelican is in a subfolder

### ISSUE THREAD

**Issue by speedmann** [getpelican/pelican-plugins#923]
Hi all,

filetime_from_git fails when the pelican files are located in a subfolder in git

```
ERROR: Could not process pages/about.md
  | InvalidGitRepositoryError: /Users/xxx/src/xxx/web
  |___
  | Traceback (most recent call last):
  |   File "/Users/xxx/.pyenv/versions/pelican/lib/python2.7/site-packages/pelican/generators.py", line 629, in generate_context
  |     context_sender=self)
  |   File "/Users/xxx/.pyenv/versions/pelican/lib/python2.7/site-packages/pelican/readers.py", line 572, in read_file
  |     context=context)
  |   File "/Users/xxx/.pyenv/versions/pelican/lib/python2.7/site-packages/pelican/contents.py", line 153, in __init__
  |     signals.content_object_init.send(self)
  |   File "/Users/xxx/.pyenv/versions/pelican/lib/python2.7/site-packages/blinker/base.py", line 267, in send
  |     for receiver in self.receivers_for(sender)]
  |   File "/Users/xxx/src/xxx/web/pelican-plugins/filetime_from_git/registration.py", line 15, in send_content_git_object_init
  |     content_git_object_init.send(content, git_content=GitContentAdapter(content))
  |   File "/Users/xxx/src/xxx/web/pelican-plugins/filetime_from_git/content_adapter.py", line 18, in __init__
  |     self.git = git_wrapper('.')
  |   File "/Users/xxx/src/xxx/web/pelican-plugins/filetime_from_git/git_wrapper.py", line 160, in git_wrapper
  |     _wrapper_cache[path] = _GitWrapper(path)
  |   File "/Users/xxx/src/xxx/web/pelican-plugins/filetime_from_git/git_wrapper.py", line 34, in __init__
  |     self.repo = Repo(os.path.abspath('.'))
  |   File "/Users/xxx/.pyenv/versions/pelican/lib/python2.7/site-packages/git/repo/base.py", line 158, in __init__
  |     raise InvalidGitRepositoryError(epath)
  | InvalidGitRepositoryError: /Users/xxx/src/xxx/web
```

The git repository is in `/Users/xxx/src/xxx/` and my pelican installation is in `/Users/xxx/src/xxx/web`

Using pelican 3.7.1 on macOS

**Comment by justinmayer** [comment]
@speedmann: Were you able to find a solution to your problem here?

**Comment by speedmann** [comment]
@justinmayer i did not find a solution untill now. I might need to retest this with newer versions.
I'll try to test this asap and let you know if i found a solution

**Comment by justinmayer** [comment]
Thanks for the update. Closing for now, but please let us know what you find out.
