### ISSUE TITLE
Mathjax broken: No MathJax URL specified

### ISSUE THREAD

**Issue by walchko** [getpelican/pelican-plugins#928]
When I try to build my site, it crashes because of render_math. This use to work nicely.

```bash
kevin@Logan pelican $ make html
pelican /Users/kevin/github/pelican/content -o /Users/kevin/github/pelican/www -s /Users/kevin/github/pelican/pelicanconf.py -D
DEBUG: Pelican version: 3.7.1
DEBUG: Python version: 3.6.1
DEBUG: Adding current directory to system path
DEBUG: Temporarily adding PLUGIN_PATHS to system path
DEBUG: Loading plugin `render_math`
DEBUG: Registering plugin `render_math`
DEBUG: Loading plugin `code_include`
DEBUG: Registering plugin `code_include`
DEBUG: Loading plugin `sitemap`
DEBUG: Registering plugin `sitemap`
DEBUG: Restoring system path
DEBUG: Found generator: <class 'sitemap.sitemap.SitemapGenerator'>
DEBUG: Template list: ['!simple/archives.html', '!simple/article.html', '!simple/author.html', '!simple/authors.html', '!simple/base.html', '!simple/categories.html', '!simple/category.html', '!simple/gosquared.html', '!simple/index.html', '!simple/page.html', '!simple/pagination.html', '!simple/period_archives.html', '!simple/tag.html', '!simple/tags.html', '!simple/translations.html', '.DS_Store', '_includes/.DS_Store', '_includes/footer.html', '_includes/header.html', '_includes/pages.html', '_includes/pagination.html', '_includes/social.html', '_includes/tags.html', 'archives.html', 'article.html', 'author.html', 'authors.html', 'base.html', 'categories.html', 'category.html', 'gosquared.html', 'index.html', 'page.html', 'pagination.html', 'period_archives.html', 'tag.html', 'tags.html', 'translations.html']
DEBUG: Read file blog/arch_linux/arch.rst -> Article
DEBUG: Signal article_generator_preread.send(ArticlesGenerator)
DEBUG: Signal article_generator_context.send(ArticlesGenerator, <metadata>)
DEBUG: Read file blog/computers/benchmark.rst -> Article
DEBUG: Read file blog/computers/clamav.rst -> Article
DEBUG: Read file blog/computers/curl.rst -> Article
DEBUG: Read file blog/computers/ethernet.rst -> Article
DEBUG: Read file blog/computers/ffmpeg.rst -> Article
DEBUG: Read file blog/computers/git.rst -> Article
DEBUG: Read file blog/computers/python.rst -> Article
DEBUG: Read file blog/computers/ssh.rst -> Article
DEBUG: Read file blog/computers/swift.rst -> Article
DEBUG: Read file blog/computers/windows.rst -> Article
DEBUG: Read file blog/cyber/cyber.rst -> Article
DEBUG: Read file blog/cyber/dpkt.rst -> Article
DEBUG: Read file blog/cyber/ip_subnetting.rst -> Article
DEBUG: Read file blog/macOS/commandline.rst -> Article
DEBUG: Read file blog/macOS/homebrew.rst -> Article
DEBUG: Read file blog/macOS/keyboard_commands.rst -> Article
DEBUG: Read file blog/macOS/ls.rst -> Article
DEBUG: Read file blog/macOS/macOS.rst -> Article
DEBUG: Read file blog/macOS/macOS_boot_disk.rst -> Article
DEBUG: Read file blog/macOS/ps4-controller.rst -> Article
DEBUG: Read file blog/macOS/virtualbox.rst -> Article
DEBUG: Read file blog/misc/misc.rst -> Article
DEBUG: Read file blog/programming/atom.rst -> Article
DEBUG: Read file blog/programming/binaries.rst -> Article
DEBUG: Read file blog/programming/files.rst -> Article
DEBUG: Read file blog/programming/html5.rst -> Article
DEBUG: Read file blog/programming/node.rst -> Article
DEBUG: Read file blog/programming/programming-i2c.rst -> Article
DEBUG: Read file blog/programming/python.rst -> Article
DEBUG: Read file blog/programming/python_modules.rst -> Article
DEBUG: Read file blog/programming/stitch.rst -> Article
DEBUG: Read file blog/raspbian/ascii_art.rst -> Article
DEBUG: Read file blog/raspbian/avahi.rst -> Article
DEBUG: Read file blog/raspbian/beacons.rst -> Article
DEBUG: Read file blog/raspbian/bluetooth.rst -> Article
DEBUG: Read file blog/raspbian/bt_sync.rst -> Article
DEBUG: Read file blog/raspbian/dlna.rst -> Article
DEBUG: Read file blog/raspbian/firewall.rst -> Article
DEBUG: Read file blog/raspbian/gpio.rst -> Article
DEBUG: Read file blog/raspbian/hardware.rst -> Article
DEBUG: Read file blog/raspbian/i2c.rst -> Article
DEBUG: Read file blog/raspbian/i2s.rst -> Article
DEBUG: Read file blog/raspbian/install.rst -> Article
DEBUG: Read file blog/raspbian/kernel.rst -> Article
DEBUG: Read file blog/raspbian/kinect.rst -> Article
DEBUG: Read file blog/raspbian/lan_protection.rst -> Article
DEBUG: Read file blog/raspbian/network.rst -> Article
DEBUG: Read file blog/raspbian/nodejs.rst -> Article
DEBUG: Read file blog/raspbian/opencv.rst -> Article
DEBUG: Read file blog/raspbian/pizero.rst -> Article
DEBUG: Read file blog/raspbian/ps4_controller.rst -> Article
DEBUG: Read file blog/raspbian/samba.rst -> Article
DEBUG: Read file blog/raspbian/sd_card.rst -> Article
DEBUG: Read file blog/raspbian/services.rst -> Article
DEBUG: Read file blog/raspbian/software.rst -> Article
DEBUG: Read file blog/raspbian/usb_hd.rst -> Article
DEBUG: Read file blog/repo/node.rst -> Article
DEBUG: Read file blog/repo/opencv.rst -> Article
DEBUG: Read file blog/repo/repo.rst -> Article
DEBUG: Read file blog/repo/zmq.rst -> Article
DEBUG: Read file blog/robots/adafruit-bno055.rst -> Article
/Users/kevin/github/pelican/content/blog/robots/adafruit-bno055.rst:: (WARNING/2) No MathJax URL specified, using local fallback (see config.html)
make: *** [html] Error 12
```

**Comment by jcbagneris** [comment]
Same problem here, render_math is the only plugin.

`DEBUG: Pelican version: 3.7.0
DEBUG: Python version: 3.6.2
DEBUG: Adding current directory to system path
DEBUG: Temporarily adding PLUGIN_PATHS to system path
DEBUG: Loading plugin `render_math`
DEBUG: Registering plugin `render_math`
DEBUG: Restoring system path
DEBUG: Read file workshop/en/moodle-calculated-questions.rst -> Article
DEBUG: Signal article_generator_preread.send(ArticlesGenerator)
/home/jcb/work/projets/writing/prof.bagneris.net/content/workshop/en/moodle-calculated-questions.rst:: (WARNING/2) No MathJax URL specified, using local fallback (see config.html)`

**Comment by justinmayer** [comment]
@barrysteyn: Any thoughts regarding these reports of `render_math` problems?

**Comment by barrysteyn** [comment]
Hi Justin

I'll answer very soon... Sorry for the delay

**Comment by jcbagneris** [comment]
Ok, finally found it, the bug is related to a change in docutils, see the last comment in https://sourceforge.net/p/docutils/bugs/319/?limit=25

As a temporary workaround, patch math.py, line 280:

```python
def mathjax_for_rst(pelicanobj, mathjax_script):
    """Setup math for RST"""
    docutils_settings = pelicanobj.settings.get('DOCUTILS_SETTINGS', {})
    docutils_settings.get['math_output'] = 'MathJax https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js'
    ...
```

Of course, a far better way would be to honor the 'math_output' setting if it exists and contains an (e.g. local) URI, and force it only if necessary.

Have fun!

**Comment by josephcslater** [comment]
Thanks! I just ran into this problem myself it this saved me untold time.

**Comment by justinmayer** [comment]
@barrysteyn: Any chance you could look at this today?

**Comment by barrysteyn** [comment]
Hi Justin - I will try look at it today...


Barry Steyn
Blog <http://doctrina.org> LinkedIn <http://ca.linkedin.com/in/barrysteyn>
GitHub <https://github.com/barrysteyn>

**Comment by MicroJoe** [comment]
Any update on this? Build is still failing without the PR's fix that fixed my problem.

**Comment by justinmayer** [comment]
Addressed via https://github.com/getpelican/pelican-plugins/commit/83bede1f1b4005034c518d4b295de67cbdc5aeba

**Comment by moorepants** [comment]
I am hitting this issue with the latest version of Pelican again. As far as I can tell the DOCUTIL_SETTINGS are not being passed to docutils from Pelican. Here is some output:

```
moorepants@garuda:moorepants.info(pelican)$ pelican -D -s pelicanconf.py 
DEBUG: Pelican version: 4.0.1
DEBUG: Python version: 3.6.7
['/home/moorepants/src/pelican-plugins']  # printed PLUGIN_PATHS
DEBUG: Adding current directory to system path
DEBUG: Temporarily adding PLUGIN_PATHS to system path
DEBUG: Loading plugin `render_math`
DEBUG: Registering plugin `render_math`
DEBUG: Loading plugin `extract_toc`
DEBUG: Registering plugin `extract_toc`
DEBUG: Restoring system path
{'math_output': 'mathjax https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.3/latest.js?config=TeX-AMS-MML_HTMLorMML'}  # printed DOCUTILS_SETTINGS inside math.py
DEBUG: Missing dependencies for md, markdown, mkd, mdown
...
DEBUG: Read file ncsrr-wrap-up.rst -> Article
options from inside docutils
[]  # printed the math_output settings from inside docuitls, note that it is empty!
ERROR: Could not process ./ncsrr-wrap-up.rst
  | SystemMessage: /home/moorepants/Websites/moorepants.info/content/ncsrr-wrap-up.rst:: (WARNING/2) No MathJax URL specified, using local fallback (see config.html)
  |___
  | Traceback (most recent call last):
  |   File "/home/moorepants/miniconda3/lib/python3.6/site-packages/docutils/writers/_html_base.py", line 1121, in visit_math
  |     self.mathjax_url = self.math_output_options[0]
  | IndexError: list index out of range
  | 
  | During handling of the above exception, another exception occurred:
  | 
  | Traceback (most recent call last):
  |   File "/home/moorepants/miniconda3/lib/python3.6/site-packages/pelican/generators.py", line 625, in generate_context
  |     context_sender=self)
  |   File "/home/moorepants/miniconda3/lib/python3.6/site-packages/pelican/readers.py", line 594, in read_file
  |     content, reader_metadata = reader.read(path)
  |   File "/home/moorepants/miniconda3/lib/python3.6/site-packages/pelican/readers.py", line 289, in read
  |     pub = self._get_publisher(source_path)
  |   File "/home/moorepants/miniconda3/lib/python3.6/site-packages/pelican/readers.py", line 284, in _get_publisher
  |     pub.publish()
  |   File "/home/moorepants/miniconda3/lib/python3.6/site-packages/docutils/core.py", line 219, in publish
  |     output = self.writer.write(self.document, self.destination)
  |   File "/home/moorepants/miniconda3/lib/python3.6/site-packages/docutils/writers/__init__.py", line 80, in write
  |     self.translate()
  |   File "/home/moorepants/miniconda3/lib/python3.6/site-packages/docutils/writers/_html_base.py", line 71, in translate
  |     self.document.walkabout(visitor)
  |   File "/home/moorepants/miniconda3/lib/python3.6/site-packages/docutils/nodes.py", line 174, in walkabout
  |     if child.walkabout(visitor):
  |   File "/home/moorepants/miniconda3/lib/python3.6/site-packages/docutils/nodes.py", line 174, in walkabout
  |     if child.walkabout(visitor):
  |   File "/home/moorepants/miniconda3/lib/python3.6/site-packages/docutils/nodes.py", line 174, in walkabout
  |     if child.walkabout(visitor):
  |   File "/home/moorepants/miniconda3/lib/python3.6/site-packages/docutils/nodes.py", line 166, in walkabout
  |     visitor.dispatch_visit(self)
  |   File "/home/moorepants/miniconda3/lib/python3.6/site-packages/docutils/nodes.py", line 1882, in dispatch_visit
  |     return method(node)
  |   File "/home/moorepants/miniconda3/lib/python3.6/site-packages/docutils/writers/_html_base.py", line 1123, in visit_math
  |     self.document.reporter.warning('No MathJax URL specified, '
  |   File "/home/moorepants/miniconda3/lib/python3.6/site-packages/docutils/utils/__init__.py", line 221, in warning
  |     return self.system_message(self.WARNING_LEVEL, *args, **kwargs)
  |   File "/home/moorepants/miniconda3/lib/python3.6/site-packages/docutils/utils/__init__.py", line 194, in system_message
  |     raise SystemMessage(msg, level)
  | docutils.utils.SystemMessage: /home/moorepants/Websites/moorepants.info/content/ncsrr-wrap-up.rst:: (WARNING/2) No MathJax URL specified, using local fallback (see config.html)
```

I'm having trouble getting further than this. My only hunch is that something changed in Pelican?

**Comment by moorepants** [comment]
I just tried with Pelican 3.7.1 and the build does not fail, but it also seems as if the math_output options are not passed to docutils:

```
(pelican371) moorepants@garuda:moorepants.info(pelican)$ make clean
[ ! -d /home/moorepants/Websites/moorepants.info/output ] || rm -rf /home/moorepants/Websites/moorepants.info/output
(pelican371) moorepants@garuda:moorepants.info(pelican)$ pelican -D -s pelicanconf.py 
DEBUG: Pelican version: 3.7.1
DEBUG: Python version: 3.6.5
['/home/moorepants/src/pelican-plugins']
DEBUG: Adding current directory to system path
DEBUG: Temporarily adding PLUGIN_PATHS to system path
DEBUG: Loading plugin `render_math`
DEBUG: Registering plugin `render_math`
DEBUG: Loading plugin `extract_toc`
ERROR: Cannot load plugin `extract_toc`
  | ModuleNotFoundError: No module named 'bs4'
DEBUG: Restoring system path
{'math_output': 'mathjax https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.3/latest.js?config=TeX-AMS-MML_HTMLorMML'}
DEBUG: Missing dependencies for md, markdown, mkd, mdown
DEBUG: Template list: ['!simple/archives.html', '!simple/article.html', '!simple/author.html', '!simple/authors.html', '!simple/base.html', '!simple/categories.html', '!simple/category.html', '!simple/gosquared.html', '!simple/index.html', '!simple/page.html', '!simple/pagination.html', '!simple/period_archives.html', '!simple/tag.html', '!simple/tags.html', '!simple/translations.html', 'archives.html', 'article.html', 'author.html', 'authors.html', 'base.html', 'categories.html', 'category.html', 'gosquared.html', 'include/analytics.html', 'include/comments.html', 'include/footer.html', 'include/header.html', 'include/pagination.html', 'include/xml_feeds.html', 'index.html', 'page.html', 'pagination.html', 'period_archives.html', 'project.hml', 'sitemap.html', 'tag.html', 'tags.html', 'translations.html']
DEBUG: Read file eme150a-fall-2015.rst -> Article
DEBUG: Signal article_generator_preread.send(ArticlesGenerator)
WARNING: Empty alt attribute for image bus-accel-data.png in /home/moorepants/Websites/moorepants.info/content/eme150a-fall-2015.rst
DEBUG: Signal article_generator_context.send(ArticlesGenerator, <metadata>)
DEBUG: Read file smud-solar-regatta-2016.rst -> Article
WARNING: Empty alt attribute for image fiberglassing-800-600.jpg in /home/moorepants/Websites/moorepants.info/content/smud-solar-regatta-2016.rst
DEBUG: Read file scipy-2017-bof.rst -> Article
DEBUG: Read file ucd-hacker-within-launch.rst -> Article
DEBUG: Read file photo-dates.rst -> Article
DEBUG: Read file drive5.rst -> Article
DEBUG: Read file cleveland-campus-district-bike-ped-assessment.rst -> Article
DEBUG: Read file hindawi-spam.rst -> Article
DEBUG: Read file pydy-code-gen.rst -> Article
options from inside docutils
[]  # printed from inside _htme_base.py in docutils, empty!
/home/moorepants/Websites/moorepants.info/content/pydy-code-gen.rst:: (WARNING/2) No MathJax URL specified, using local fallback (see config.html)
```

**Comment by moorepants** [comment]
I think this is a bug in docutils (or either pelican is using docutils incorrectly). This function in docutils core.py:

```
    def setup_option_parser(self, usage=None, description=None,
                            settings_spec=None, config_section=None,
                            **defaults):
        if config_section:
            if not settings_spec:
                settings_spec = SettingsSpec()
            settings_spec.config_section = config_section
            parts = config_section.split()
            if len(parts) > 1 and parts[-1] == 'application':
                settings_spec.config_section_dependencies = ['applications']
        #@@@ Add self.source & self.destination to components in future?
        option_parser = OptionParser(
            components=(self.parser, self.reader, self.writer, settings_spec),
            defaults=defaults, read_config_files=True,
            usage=usage, description=description)
        return option_parser
```

is supposed to return the settings with any overrides applied. `defaults` does contain the overrides applied by pelican (or render_math) but option_parser does not seem to have the settings from pelican/render_math. Subsequently option_parser.get_default_values() is called and does not return a dictionary with any of the user supplied programmatic settings.

**Comment by avaris** [comment]
FYI, `pelican 3.7.1` build failed. What changed in `pelican 4` is that a failed RST parse for a single file no longer terminates `pelican`. It's logged and `pelican` continues.

**Comment by moorepants** [comment]
I do not define DOCUTILS_SETTINGS, although I've tried that and the settings dont' seem to be applied either. I am using the master branch of pelican-plugins.

**Comment by moorepants** [comment]
I finally figured it out. I actually had a docutils.conf file in the directory that I wasn't aware of that was overriding the setting. The lost hours....
