### ISSUE TITLE
module 'gist_directive' has no attribute 'register'

### ISSUE THREAD

**Issue by walchko** [getpelican/pelican-plugins#929]
The `gist_directive` (written by @ionelmc) crashes.

```bash
pelican /Users/kevin/github/pelican/content -o /Users/kevin/github/pelican/www -s /Users/kevin/github/pelican/pelicanconf.py -D
DEBUG: Pelican version: 3.7.1
DEBUG: Python version: 3.6.1
DEBUG: Adding current directory to system path
DEBUG: Temporarily adding PLUGIN_PATHS to system path
DEBUG: Loading plugin `render_math`
DEBUG: Registering plugin `render_math`
DEBUG: Loading plugin `code_include`
DEBUG: Registering plugin `code_include`
DEBUG: Loading plugin `sitemap`
DEBUG: Registering plugin `sitemap`
DEBUG: Loading plugin `gist_directive`
DEBUG: Registering plugin `gist_directive`
CRITICAL: AttributeError: module 'gist_directive' has no attribute 'register'
Traceback (most recent call last):
  File "/usr/local/bin/pelican", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/pelican/__init__.py", line 393, in main
    pelican, settings = get_instance(args)
  File "/usr/local/lib/python3.6/site-packages/pelican/__init__.py", line 382, in get_instance
    return cls(settings), settings
  File "/usr/local/lib/python3.6/site-packages/pelican/__init__.py", line 53, in __init__
    self.init_plugins()
  File "/usr/local/lib/python3.6/site-packages/pelican/__init__.py", line 80, in init_plugins
    plugin.register()
AttributeError: module 'gist_directive' has no attribute 'register'
make: *** [html] Error 1
```

**Comment by ionelmc** [comment]
Probably the import in `__init__.py` is wrong, try editing it to `from .gist_directive import *`.

**Comment by walchko** [comment]
that worked ... thanks! :tada:
