### ISSUE TITLE
simple_footnotes: TypeError: sequence item 15: expected string or Unicode, NoneType found

### ISSUE THREAD

**Issue by ahmetb** [getpelican/pelican-plugins#930]
When I install the latest `simple_footnotes` on `pelican==3.7.1` and `html5lib=0.999999999`, and compile the text below, I get error:

```
CRITICAL: TypeError: sequence item 15: expected string or Unicode, NoneType found
```

The content: 
```markdown
2. **API server will assign initializers to the new resources:** When you submit
   a Deployment object to the apiserver, it will update Deployment's
   `metadata.initalizers.pending` and add the "myproxy" value there. This field
   shows of initializers currently assigned to the resource.[ref]To be accurate,
   it's not the apiserver adding the initializers. There's an admission
   controller plugin called “Initializer”, which makes this whole initialization
   story possible. It's enabled by adding the
   <nobr>`--admission-controller=Initializer`</nobr> flag to the
   kube-apiserver.[/ref]
```

When I remove `[ref]` tags, it compiles fine.

I think the simple_footnotes can return a better error for at least debugging. Let me know if you need help troubleshooting.

@johnmarkschofield I saw you made a recent fix to the plugin about unicode, I'm not sure if this is related. Any ideas?

**Comment by ahmetb** [comment]
The unit test for this plugin also seems to be failing

```
$ python test_simple_footnotes.py
.F
======================================================================
FAIL: test_simple (__main__.TestFootnotes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_simple_footnotes.py", line 22, in test_simple
    ('words<sup id="sf-article-1-back"><a title="footnote" '
  File "test_simple_footnotes.py", line 18, in _expect
    self.assertEqual(art._content, expected_output)
AssertionError: u'words<sup id=sf-article-1-back><a title=footnote href=#sf-article-1 class=simp [truncated]... != u'words<sup id="sf-article-1-back"><a title="footnote" href="#sf-article-1" clas [truncated]...
- words<sup id=sf-article-1-back><a title=footnote href=#sf-article-1 class=simple-footnote>1</a></sup>end<ol class=simple-footnotes><li id=sf-article-1>footnote <a href=#sf-article-1-back class=simple-footnote-back>\u21a9</a></li></ol>
+ words<sup id="sf-article-1-back"><a title="footnote" href="#sf-article-1" class="simple-footnote">1</a></sup>end<ol class="simple-footnotes"><li id="sf-article-1">footnote <a href="#sf-article-1-back" class="simple-footnote-back">\u21a9</a></li></ol>


----------------------------------------------------------------------
Ran 2 tests in 0.011s

FAILED (failures=1)
```

**Comment by justinmayer** [comment]
May be addressed by https://github.com/getpelican/pelican-plugins/pull/864. Would you please test current master and let us know?

**Comment by ahmetb** [comment]
It works now, thanks.
