### ISSUE TITLE
[autopages] Doesn't like the {filename} ?

### ISSUE THREAD

**Issue by bobman38** [getpelican/pelican-plugins#951]
I am testing autopages but it seems it doesn't like the {filename} thing.

I am on Pelican 3.7.1

I have that in my category page:

    ![equipe]({filename}/images/equipe.jpg "equipe")

and then it pop that:

    CRITICAL: KeyError: 'filenames'
    Traceback (most recent call last):
      File "/home/julien/.virtualenvs/pelican/bin/pelican", line 11, in <module>
       sys.exit(main())
      File "/home/julien/.virtualenvs/pelican/lib/python3.5/site-packages/pelican/__init__.py", line 465, in main
        pelican.run()
      File "/home/julien/.virtualenvs/pelican/lib/python3.5/site-packages/pelican/__init__.py", line 179, in run
        p.generate_output(writer)

Any ideas ? :)

**Comment by bobman38** [comment]
OK just pushed a PR that fix that on my install !
