### ISSUE TITLE
[Bug] [filetime_from_git] TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by Kristinita** [getpelican/pelican-plugins#977]
Ping all contributors of `filetime_from_git`: @cscutcher, @mbudde, @vosskuhle, @jar1karp, @Aetf.

### 1. Summary

I can't begin to use `filetime_from_git` plugin. Possibly, it because `filetime_from_git` [**not support newest Python versions**](https://stackoverflow.com/q/33054527/5951529) at the time.

### 2. Environment

+ Windows 10 Enterprise LTSB 64-bit EN,
+ Python 3.6.4,
+ Pelican 3.7.1,
+ Python Markdown 2.6.11,
+ gitpython 2.1.8,
+ filetime_from_git — newest version at the time.

### 3. Configuration

Part of my `pelicanconf.py` file:

```python
PLUGIN_PATHS = ['pelican-plugins']
PLUGINS = [
    'filetime_from_git'
]
```

Part of my `SashaTest.md` file:

```markdown
Date: 2017-04-04 04:14:07
Modified: 2018-01-12 08:44:36
```

### 4. Steps to reproduce

I run in command line:

    pelican content -s pelicanconf.py --debug > FiletimeFromGit.txt 2>&1

### 5. Expected behavior

Successful working `filetime_from_git`

### 6. Actual behavior

I have `SashaTest.md` file in `content` folder:

**If** no `Date:` and `Modified:` variables in `SashaTest.md`:

```python
DEBUG: Popen(['git', 'ls-files', b'D:\\SashaPelicanTest\\content\\SashaTest\\SashaTest.md', '--error-unmatch'], cwd=D:\SashaPelicanTest, universal_newlines=False, shell=None)
ERROR: Could not process SashaTest\SashaTest.md
  | TypeError: a bytes-like object is required, not 'str'
  |___
  | Traceback (most recent call last):
  |   File "c:\python36\lib\site-packages\pelican\generators.py", line 523, in generate_context
  |     context_sender=self)
  |   File "c:\python36\lib\site-packages\pelican\readers.py", line 572, in read_file
  |     context=context)
  |   File "c:\python36\lib\site-packages\pelican\contents.py", line 153, in __init__
  |     signals.content_object_init.send(self)
  |   File "c:\python36\lib\site-packages\blinker\base.py", line 267, in send
  |     for receiver in self.receivers_for(sender)]
  |   File "c:\python36\lib\site-packages\blinker\base.py", line 267, in <listcomp>
  |     for receiver in self.receivers_for(sender)]
  |   File "D:\SashaPelicanTest\pelican-plugins\filetime_from_git\registration.py", line 15, in send_content_git_object_init
  |     content_git_object_init.send(content, git_content=GitContentAdapter(content))
  |   File "c:\python36\lib\site-packages\blinker\base.py", line 267, in send
  |     for receiver in self.receivers_for(sender)]
  |   File "c:\python36\lib\site-packages\blinker\base.py", line 267, in <listcomp>
  |     for receiver in self.receivers_for(sender)]
  |   File "D:\SashaPelicanTest\pelican-plugins\filetime_from_git\actions.py", line 40, in filetime_from_git
  |     if git_content.is_managed_by_git():
  |   File "c:\python36\lib\site-packages\pelican\utils.py", line 173, in __call__
  |     value = self.func(*args)
  |   File "D:\SashaPelicanTest\pelican-plugins\filetime_from_git\content_adapter.py", line 41, in is_managed_by_git
  |     return self.git.is_file_managed_by_git(self.content.source_path)
  |   File "D:\SashaPelicanTest\pelican-plugins\filetime_from_git\git_wrapper.py", line 44, in is_file_managed_by_git
  |     with_exceptions=False)
  |   File "c:\python36\lib\site-packages\git\cmd.py", line 732, in execute
  |     **subprocess_kwargs
  |   File "c:\python36\lib\subprocess.py", line 709, in __init__
  |     restore_signals, start_new_session)
  |   File "c:\python36\lib\subprocess.py", line 971, in _execute_child
  |     args = list2cmdline(args)
  |   File "c:\python36\lib\subprocess.py", line 461, in list2cmdline
  |     needquote = (" " in arg) or ("\t" in arg) or not arg
  | TypeError: a bytes-like object is required, not 'str'
```

**If**:

```markdown
Date: 2017-04-04 04:14:07
Modified: 2018-01-12 08:44:36
```

Traceback:

```python
DEBUG: Popen(['git', 'ls-files', b'D:\\SashaPelicanTest\\content\\SashaTest\\SashaTest.md', '--error-unmatch'], cwd=D:\SashaPelicanTest, universal_newlines=False, shell=None)
ERROR: Could not process SashaTest\SashaTest.md
  | TypeError: a bytes-like object is required, not 'str'
  |___
  | Traceback (most recent call last):
  |   File "c:\python36\lib\site-packages\pelican\generators.py", line 523, in generate_context
  |     context_sender=self)
  |   File "c:\python36\lib\site-packages\pelican\readers.py", line 572, in read_file
  |     context=context)
  |   File "c:\python36\lib\site-packages\pelican\contents.py", line 153, in __init__
  |     signals.content_object_init.send(self)
  |   File "c:\python36\lib\site-packages\blinker\base.py", line 267, in send
  |     for receiver in self.receivers_for(sender)]
  |   File "c:\python36\lib\site-packages\blinker\base.py", line 267, in <listcomp>
  |     for receiver in self.receivers_for(sender)]
  |   File "D:\SashaPelicanTest\pelican-plugins\filetime_from_git\registration.py", line 15, in send_content_git_object_init
  |     content_git_object_init.send(content, git_content=GitContentAdapter(content))
  |   File "c:\python36\lib\site-packages\blinker\base.py", line 267, in send
  |     for receiver in self.receivers_for(sender)]
  |   File "c:\python36\lib\site-packages\blinker\base.py", line 267, in <listcomp>
  |     for receiver in self.receivers_for(sender)]
  |   File "D:\SashaPelicanTest\pelican-plugins\filetime_from_git\actions.py", line 40, in filetime_from_git
  |     if git_content.is_managed_by_git():
  |   File "c:\python36\lib\site-packages\pelican\utils.py", line 173, in __call__
  |     value = self.func(*args)
  |   File "D:\SashaPelicanTest\pelican-plugins\filetime_from_git\content_adapter.py", line 41, in is_managed_by_git
  |     return self.git.is_file_managed_by_git(self.content.source_path)
  |   File "D:\SashaPelicanTest\pelican-plugins\filetime_from_git\git_wrapper.py", line 44, in is_file_managed_by_git
  |     with_exceptions=False)
  |   File "c:\python36\lib\site-packages\git\cmd.py", line 732, in execute
  |     **subprocess_kwargs
  |   File "c:\python36\lib\subprocess.py", line 709, in __init__
  |     restore_signals, start_new_session)
  |   File "c:\python36\lib\subprocess.py", line 971, in _execute_child
  |     args = list2cmdline(args)
  |   File "c:\python36\lib\subprocess.py", line 461, in list2cmdline
  |     needquote = (" " in arg) or ("\t" in arg) or not arg
  | TypeError: a bytes-like object is required, not 'str'
```

**If**:

```python
Date: 
Modified: 
```

```python
ERROR: Could not process SashaTest\SashaTest.md
  | ValueError: '' is not a valid date
  |___
  | Traceback (most recent call last):
  |   File "c:\python36\lib\site-packages\pelican\utils.py", line 236, in get_date
  |     return dateutil.parser.parse(string, default=default)
  |   File "c:\python36\lib\site-packages\dateutil\parser.py", line 1182, in parse
  |     return DEFAULTPARSER.parse(timestr, **kwargs)
  |   File "c:\python36\lib\site-packages\dateutil\parser.py", line 562, in parse
  |     raise ValueError("String does not contain a date.")
  | ValueError: String does not contain a date.
  | 
  | During handling of the above exception, another exception occurred:
  | 
  | Traceback (most recent call last):
  |   File "c:\python36\lib\site-packages\pelican\generators.py", line 523, in generate_context
  |     context_sender=self)
  |   File "c:\python36\lib\site-packages\pelican\readers.py", line 526, in read_file
  |     content, reader_metadata = reader.read(path)
  |   File "c:\python36\lib\site-packages\pelican\readers.py", line 297, in read
  |     metadata = self._parse_metadata(self._md.Meta)
  |   File "c:\python36\lib\site-packages\pelican\readers.py", line 279, in _parse_metadata
  |     output[name] = self.process_metadata(name, value[0])
  |   File "c:\python36\lib\site-packages\pelican\readers.py", line 112, in process_metadata
  |     return METADATA_PROCESSORS[**name**](value, self.settings)
  |   File "c:\python36\lib\site-packages\pelican\readers.py", line 39, in <lambda>
  |     'date': lambda x, y: get_date(x.replace('_', ' ')),
  |   File "c:\python36\lib\site-packages\pelican\utils.py", line 238, in get_date
  |     raise ValueError('{0!r} is not a valid date'.format(string))
  | ValueError: '' is not a valid date
```

I don't know what else should I do, that `filetime_from_git` works.

Thanks.

**Comment by justinmayer** [comment]
@Kristinita: Were you able to find a solution to your problem here? (See also: #923 #968)

**Comment by Kristinita** [comment]
@justinmayer , **#1002** patch fix this problem, but permalinks plugin (which is dependent on `filetime_from_git`) doesn't work, see **#1011**. Thanks.

**Comment by justinmayer** [comment]
Thanks for the update @Kristinita. Let's mark this as fixed by the above PR and address that plugin's problem separately.
