### ISSUE TITLE
[asciidoc_reader] Upgrade breaks umlauts with "'ascii' codec can't decode byte 0xc3 in position 19: ordinal not in range'"

### ISSUE THREAD

**Issue by bentolor** [getpelican/pelican-plugins#995]
Upgrading from c478eb7e0dc3fdaa1e36e5829ea00cf0f0af1bb9 to 8de8e847ce78e53b62dfdcd7e0e1923614adead5 breaks the Asciidoc input for me

I have asciidoc and asciidoctor installed:

```
$ asciidoctor -v ; asciidoc --version 
Asciidoctor 1.5.6.1 [http://asciidoctor.org]
Runtime Environment (ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
asciidoc 8.6.9
```

```
Starting up Pelican and HTTP server
DEBUG: Pelican version: 3.7.1
DEBUG: Python version: 2.7.12
DEBUG: Adding current directory to system path
DEBUG: Temporarily adding PLUGIN_PATHS to system path
DEBUG: Loading plugin `asciidoc_reader`
DEBUG: Registering plugin `asciidoc_reader`
DEBUG: Restoring system path
  --- AutoReload Mode: Monitoring `content`, `theme` and `settings` for changes. ---

-> Modified: content, theme, settings. re-generating...
DEBUG: Template list: [u'!simple/archives.html', u'!simple/article.html', u'!simple/author.html', u'!simple/authors.html', u'!simple/base.html', u'!simple/categories.html', u'!simple/category.html', u'!simple/gosquared.html', u'!simple/index.html', u'!simple/page.html', u'!simple/pagination.html', u'!simple/period_archives.html', u'!simple/tag.html', u'!simple/tags.html', u'!simple/translations.html', u'analytics.html', u'archives.html', u'article.html', u'author.html', u'authors.html', u'base.html', u'categories.html', u'category.html', u'common_seo.html', u'disqus_count.html', u'gosquared.html', u'index.html', u'page.html', u'pagination.html', u'period_archives.html', u'search.html', u'tag.html', u'tags.html', u'tipue_search.html', u'translations.html']

…

DEBUG: Read file readablez/76_Schoene_Bilder.adoc -> Article
ERROR: Could not process readablez/76_Schoene_Bilder.adoc
  | UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 19: ordinal not in range(128)
  |___
  | Traceback (most recent call last):
  |   File "/usr/local/lib/python2.7/dist-packages/pelican/generators.py", line 523, in generate_context
  |     context_sender=self)
  |   File "/usr/local/lib/python2.7/dist-packages/pelican/readers.py", line 572, in read_file
  |     context=context)
  |   File "/usr/local/lib/python2.7/dist-packages/pelican/contents.py", line 101, in __init__
  |     settings.get('SLUG_SUBSTITUTIONS', ()))
  |   File "/usr/local/lib/python2.7/dist-packages/pelican/utils.py", line 262, in slugify
  |     value = Markup(value).striptags()
  |   File "/usr/local/lib/python2.7/dist-packages/markupsafe/__init__.py", line 75, in __new__
  |     return text_type.__new__(cls, base)
  | UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 19: ordinal not in range(128)
…
```

I tried saving the file `readablez/76_Schoene_Bilder.adoc` in UTF-8, UTF-8 with BOM and ISO-8859-15 which did not help. 

I assume the bug is caused by the switch over to Asciidoctor (which I appreciate) and some missing encoding passing?

**Comment by bentolor** [comment]
CC @jeffrimko

**Comment by jeffrimko** [comment]
Hi @bentolor, sorry for the delay. Started looking into this just now. Looks like it is a Python 2 specific problem and it seems to only affect metadata (title, tags, etc). Umlauts in the content body seem to be okay. Investigating more now.

**Comment by bentolor** [comment]
Hi @jeffrimko, thanks for your timely feedback. Glad you were already able to reproduce the issue. 

>  …it seems to only affect metadata (title, tags, etc). 
This matches the file which contains Umlaute in the page title. The Umlauts in the body were not affected

**Comment by jeffrimko** [comment]
Okay, thanks for the info. If you need a better temporary solution, add the following after the `import` statements in your local `asciidoc_reader.py` file:

    import sys
    reload(sys)
    sys.setdefaultencoding("utf-8")

This will allow you to keep the umlauts in the title. I hope to commit a fix later today.

**Comment by justinmayer** [comment]
Ostensibly addressed via linked PR.

**Comment by bentolor** [comment]
Can confirm, this resolves the issue. Thank you very much @jeffrimko for you fast fix! This helps a lot.
